#!/usr/bin/env python3
"""
Diagram Structure Generator

Generates diagram structure for Excalidraw.
"""

import sys
import json
from datetime import datetime


DIAGRAM_TEMPLATE = """# Diagram: {title}

Created: {date}

## Elements

### Boxes
{boxes}

### Connections
{connections}

### Labels
{labels}

---

## Excalidraw Structure (JSON)

```json
{structure}
```

---

*Generated by Canvas Diagram Studio*
"""


def generate_diagram(title, elements=None):
    """Generate diagram structure."""
    structure = {
        "type": "excalidraw",
        "version": 2,
        "source": "Canvas Diagram Studio",
        "elements": elements or [],
        "appState": {"gridSize": 20},
    }

    print(
        DIAGRAM_TEMPLATE.format(
            title=title,
            date=datetime.now().strftime("%Y-%m-%d"),
            boxes="[Add your boxes here]",
            connections="[Add arrows/connections here]",
            labels="[Add text labels here]",
            structure=json.dumps(structure, indent=2),
        )
    )


if __name__ == "__main__":
    if len(sys.argv) < 2:
        print("Usage: python create-diagram.py <title>")
        sys.exit(1)

    generate_diagram(" ".join(sys.argv[1:]))
