#!/usr/bin/env python3
"""
Screen Generator Helper

Generates screen structure from prompt.
"""

import sys
from datetime import datetime


SCREEN_TEMPLATE = """# Screen: {title}

Generated: {date}

## Prompt
{prompt}

## Structure

### Layout
- Header: [header description]
- Sidebar: [sidebar description]  
- Main Content: [main content description]
- Footer: [footer description]

### Components
{components}

### Styling Notes
- Primary Color: #3B82F6
- Background: #0a0a0a
- Text: #fafafa

---

## MCP Command

```json
{{
  "tool": "generate_screen",
  "params": {{
    "prompt": "{prompt}",
    "style": "premium",
    "output": "{filename}.pen"
  }}
}}
```

---

*Generated by Pencil Design Studio*
"""


def generate_screen(title, prompt="Modern interface"):
    """Generate screen structure."""
    print(
        SCREEN_TEMPLATE.format(
            title=title,
            date=datetime.now().strftime("%Y-%m-%d"),
            prompt=prompt,
            components="[List components here]",
            filename=title.lower().replace(" ", "-"),
        )
    )


if __name__ == "__main__":
    if len(sys.argv) < 2:
        print("Usage: python generate-screen.py <title> [prompt]")
        sys.exit(1)

    title = sys.argv[1]
    prompt = " ".join(sys.argv[2:]) if len(sys.argv) > 2 else "Modern interface"
    generate_screen(title, prompt)
