#!/usr/bin/env python3
"""
Content Generator Helper

Generates content templates and helps structure articles/posts.
"""

import sys
from pathlib import Path
from datetime import datetime


def generate_blog_post(title, topic):
    """Generate a blog post template."""
    template = f"""# {title}

> {topic}

*Published: {datetime.now().strftime("%Y-%m-%d")}*

## Introduction

[Hook the reader with a compelling opening]

## Main Content

### Section 1
[Content here]

### Section 2
[Content here]

## Conclusion

[Summarize key points and call to action]

---

*Generated by Content Generation Skill*
"""
    return template


def generate_social_post(platform, topic):
    """Generate a social media post template."""
    templates = {
        "twitter": f"🧵 {topic}\n\n[Thread starting here]\n\n#content #topic",
        "linkedin": f"💼 {topic}\n\n[Professional insights here]\n\n#professional #growth",
        "instagram": f"📸 {topic}\n\n[Visual description]\n\n#inspire #create",
    }
    return templates.get(platform, f"📝 {topic}\n\n[Content here]")


def main():
    """Main entry point."""
    if len(sys.argv) < 3:
        print("Usage: python generate-content.py <type> <title/topic> [platform]")
        print("Types: blog, social")
        return

    content_type = sys.argv[1]
    title = sys.argv[2]

    if content_type == "blog":
        print(generate_blog_post(title, "Topic description"))
    elif content_type == "social":
        platform = sys.argv[3] if len(sys.argv) > 3 else "twitter"
        print(generate_social_post(platform, title))
    else:
        print(f"Unknown type: {content_type}")


if __name__ == "__main__":
    main()
